### PR TITLE
chore + fix

### PR DESCRIPTION
**Pull request by SUP2Ak**
- Remove code useless
- Fix fxmanifest client_script (you open object: client_scripts) and order to load files

### CODE REVIEW

**Comment by SUP2Ak** [comment]
lol

**Comment by SUP2Ak** [comment]
You make me laugh, close pull request but copy past code in this pull request ... 🤣

**Comment by nlckl** [comment]
i dont know github, sorry. I think this was for u to send me better code improvements etc.

**Comment by SUP2Ak** [comment]
🤦

**Pull request closed without merging**
